Repository roadrunner-server/goridge, pull requests merged in 2020-03, with the labels that each got.

#42 Fix typo in max buffer length
  .travis.yml
  README.md
  examples/server.go
  go.mod
  go.sum
  relay.go
  tests/server.go
Labels: bug

#44 performance update, bors, json
  .coveralls.yml
  .github/workflows/ci-build.yml
  .travis.yml
  README.md
  bors.toml
  client.go
  codec.go
  go.mod
  go.sum
  pipe.go
  socket.go
Labels: A-other, A-tests, B-performance, C-enhancement

#46 2.3.0 release
  CHANGELOG.md
Labels: C-enhancement

#47 update golang modules to v2
  CHANGELOG.md
  go.mod
Labels: A-other, C-enhancement

#49 feat: allow user to customize codec relay
  codec.go
Labels: A-other, C-enhancement
