Repository roadrunner-server/goridge, pull requests merged in 2020-04, with the labels that each got.

#50 unix sockets support on windows
  .github/workflows/ci-build.yml
  Makefile
  README.md
  binary.go
  binary_test.go
  bors.toml
  client.go
  client_server_test.go
  examples/server.go
  php-src/SocketRelay.php
  pipe.go
  socket.go
Labels: A-network, C-enhancement, O-windows

#51 Reduce syscalls usage
  composer.json
  php-src/RPC.php
  php-src/RelayInterface.php
  php-src/SocketRelay.php
  php-src/StreamRelay.php
  php-src/functions.php
Labels: A-other, B-performance, C-enhancement

#55 Update changelog
  CHANGELOG.md
Labels: A-docs

#59 Initiate RPC defaults
  php-src/RPC.php
Labels: A-network, B-bug
