Repository roadrunner-server/goridge, pull requests merged in 2020-05, with the labels that each got.

#58 Add tests execution during build
  .github/workflows/ci-build.yml
  .gitignore
  php-src/RPC.php
  php-src/RelayInterface.php
  php-src/SocketRelay.php
  php-src/StreamRelay.php
  tests/Cases/Legacy/Relay.php
  tests/Cases/Legacy/TCPSocketTest.php
  tests/Cases/Legacy/UnixSocketTest_.php
  tests/Cases/RPCTest.php
  tests/Cases/TCPSocketTest.php
  tests/Cases/UnixSocketTest_.php
  tests/Dockerfile
  tests/docker-compose.yml
  tests/go.mod
  tests/go.sum
  tests/server.go
Labels: A-tests, C-enhancement

#63 release 2.4.0
  CHANGELOG.md
Labels: A-other

#66 Fix bc break
  src/RelayInterface.php
  tests/Cases/Legacy/Relay.php
Labels: A-other, B-regression

#67 Update functions.php
  src/functions.php
Labels: A-other, B-regression

#68 Add phpstan
  composer.json
  phpstan.neon.dist
  src/RPC.php
  src/Relay.php
  src/RelayInterface.php
  src/SendPackageRelayInterface.php
  src/SocketRelay.php
  src/StreamRelay.php
  src/StringableRelayInterface.php
  tests/Cases/Legacy/Relay.php
  tests/Cases/RPCTest.php
  tests/Cases/RelayFactoryTest.php
  tests/Cases/SocketRelayTest.php
  tests/go.mod
  tests/server.go
Labels: A-tests, C-enhancement

#69 performance optimizations
  .github/workflows/ci-build.yml
  .gitignore
  .golangci.yml
  client.go
  composer.json
  go.mod
  pipe.go
  pipe_test.go
  relay.go
  socket.go
  tests/go.mod
  tests/go.sum
  utils.go
  utils_test.go
Labels: A-tests, B-performance, C-enhancement

#71 release 2.4.2
  CHANGELOG.md
Labels: A-other

#72 bugfix in the Receive function
  alloc.go
  alloc_test.go
  pipe.go
  pipe_test.go
  socket.go
  socket_test.go
Labels: B-bug

#73 Bugfix/makeslice len out of range
  alloc.go
  alloc_windows.go
  constants.go
  pipe.go
  pipe_test.go
  socket.go
  socket_test.go
Labels: B-crash, B-regression
